# Generated by Django 5.2.7 on 2025-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_contact_userprofile_userprofileimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
