# Generated by Django 5.2.7 on 2025-10-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagereadstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nickname',
            new_name='name',
        ),
    ]
